# config/yolosplit.yaml

# DEFAULT CONFIGURATIONS
default:
  device: cuda
  font_path: config/fonts/DejaVuSans-Bold.ttf
  save_layer_images: false

# LOGGING CONFIGURATIONS
logging:
  log_level: INFO
  log_file: logs/app.log

# MODEL CONFIGURATIONS
model:
  model_name: yolov8s
  version: null
  pretrained: false
  weight_path: data/onion/weights/best.pt
  input_size: [3, 224, 224]
  split_layer: 3
  save_layers: [2, 4, 6]
  num_classes: 2
  mode: eval
  depth: 2
  flush_buffer_size: 100
  warmup_iterations: 10
  log_file: logs/yolosplit.log

# DATASET CONFIGURATIONS
dataset:
  module: onion
  class: OnionDataset
  args:
    root: data/onion
    class_names: ["with_weeds", "without_weeds"]
    img_directory: data/onion/testing
    transform: null
    max_samples: -1

# DATALOADER CONFIGURATIONS
dataloader:
  batch_size: 1
  shuffle: false
  num_workers: 4
  collate_fn: onion_collate

# COMPRESSION CONFIGURATIONS
compression:
  clevel: 3
  filter: SHUFFLE
  codec: ZSTD
